### ISSUE TITLE
[NEW] Different number of step for each variable

### ISSUE THREAD

**Issue by gcoimbra** [gugarosa/opytimizer#15]
**Is your feature request related to a problem? Please describe.**
It's not

**Describe the solution you'd like**
I'd like a different step size for each 

**Additional context**
Sometimes variables are less sensible than others. Some are integers. Is there anyway to use a different step for each one?

**Comment by gugarosa** [comment]
Are you referring to the `step` argument when instantiating a `GridSpace`?

**Comment by gcoimbra** [comment]
> Are you referring to the `step` argument when instantiating a `GridSpace`?

Yes!

**Comment by gugarosa** [comment]
Ok, seems to be sweet! Just implemented that on last commit (https://github.com/gugarosa/opytimizer/commit/b9ff09fd800957bad73ee3019d80be50d28e4415), though it will be available through `pip` within the next release.

`step` argument will now be a tuple specifying the amount of interval that should be used for each decision variable. Additionally, it has to be the same size of `lower_bound` and `upper_bound`.

Thank you for your suggestion and best regards,
Gustavo.
