### ISSUE TITLE
[REG] How to get best agent values?

### ISSUE THREAD

**Issue by amir1m** [gugarosa/opytimizer#18]
Hello,
I am following the [tutorial](https://github.com/gugarosa/opytimizer/wiki/Tutorial:-Your-first-optimization).
After running `opt.start()`  how do we get the optimized parameters? `opt` object has `history. best_agent ` attributes, is there way to directly get the best parameters? 

Also, by default it does minimization or maximization?

**Comment by gugarosa** [comment]
Hello amir1m! I hope everything is going well with you!

Usually, we use the `history` object to get the values over the iterations, which you can retrieve using the `history.get()` method. On the other hand, if you just need to access the value of the best parameters, you can directly use the following:

```
# The best agent's position stores the best parameters
best_params = opt.best_agent.position

# Note that as we use a (n_variables, n_dimensions) tensor, you need to index both dimensions to retriever the parameters 
# In most cases, we use n_dimensions=1, so you can access them with its first index
x1 = best_params[0][0]
x2 = best_params[1][0]
x3 = best_params[2][0]
...
xN = best_params[N-1][0]
```

And finally, by default, we focus on **minimization**.

I hope that I could help you at all, but if you have any problems or concerns, please let me know!

Best regards,
Gustavo.

**Comment by amir1m** [comment]
Got it. Thanks @gugarosa ! Working as you mentioned.
