### ISSUE TITLE
[REG]

### ISSUE THREAD

**Issue by tumu1234** [gugarosa/opytimizer#28]
## Optimization time problem

Hello, author, why it takes 5 hours to optimize SVR's hyperparameters with PSO and AOA? Is there something wrong with me？

**Comment by gugarosa** [comment]
Hello! I hope everything is going well with you.

Try lowering the number of agents and iterations. Usually, meta-heuristics performs n_agents x n_iterations fitness function evaluations, and it heavily depends on the time an evaluation is.

SVR over a complete dataset/full-pass might take a while, and thus the whole optimization problems is bounded by the time of such a fitness function.

Best regards,
Gustavo.

**Comment by tumu1234** [comment]
Ok, thank you for your explanation and wish us all the best

**Comment by gugarosa** [comment]
No problems! Just please let me know if anything else comes up!

All the best for us all, always!!
