### ISSUE TITLE
[NEW]

### ISSUE THREAD

**Issue by tumu1234** [gugarosa/opytimizer#31]
Dear author 
Hello, I want to use chaotic mapping to improve the initial amount of intelligent evolutionary algorithm, but can not start, do you have any suggestions。
I look forward to your suggestion。

**Comment by gugarosa** [comment]
Hello @tumu1234 ! I hope everything is going well with you.

I am not sure if I follow your question, but you can use the Darcy Optimization Algorithm: https://github.com/gugarosa/opytimizer/blob/master/opytimizer/optimizers/misc/doa.py

It is already an evolutionary algorithm that uses chaotic maps.

Thank you and best regards,
Gustavo.
