### ISSUE TITLE
[REG] v3.1.3 pypi release 

### ISSUE THREAD

**Issue by joaquinco** [gugarosa/opytimizer#39]
## Release to pypi

Can you push the latest release to pypi?

**Comment by gugarosa** [comment]
Hello @joaquinco!

Sorry about that, the workflow that was supposed to release the package failed. Nevertheless, I have manually uploaded 3.1.3 and 3.1.4 to PyPI.

Best regards,
Gustavo.

**Comment by joaquinco** [comment]
Thank you!
