### ISSUE TITLE
[REG] Strange testing pattern

### ISSUE THREAD

**Issue by lzfelix** [gugarosa/opytimizer#6]
Hi, while browsing through the tests I found the following construction several times. Can you please explain the rationale behind it?

```python
try:
    new_optimizer.hyperparams = 1  # (1)
except:
    new_optimizer.hyperparams = {
        'w': 1.5
    }
```

If you're executing `(1)` hoping for it to fail, then that should be asserted as well.

Thanks,
Felix

**Comment by gugarosa** [comment]
Hello! I hope everything is all right!

As we have discussed yesterday, it is just a trick to raise the exception and make use of the corresponding line, for asserting the line while running the coverage tests.

Nevertheless, we will further investigate if the `pytest.exceptions` module is helpful to design this approach, as suggested by you.

Best regards,
Gustavo.
