### ISSUE TITLE
[BUG] AttributeError: 'History' object has no attribute 'show'

### ISSUE THREAD

**Issue by justinTM** [gugarosa/opytimizer#9]
**Describe the bug**

It looks like there is no `show()` method for the returned opytimizer history.

**To Reproduce**
1. Follow the steps from the wiki [Tutorial: Your first optimization](https://github.com/gugarosa/opytimizer/wiki/Tutorial:-Your-first-optimization)
    1. Run the optimizer with o.start():
    ```o = Opytimizer(space=s, optimizer=p, function=f)```
    ```history = o.start()```
    1. Show the history:
    ```history.how()```

**Expected behavior**
Not sure what I expected, just curious :)

**Screenshots**
```
2020-01-02 13:26:28,270 - opytimizer.optimizers.fa — INFO — Iteration 1000/1000
2020-01-02 13:26:28,278 - opytimizer.optimizers.fa — INFO — Fitness: 4.077875713322641e-14
2020-01-02 13:26:28,279 - opytimizer.optimizers.fa — INFO — Position: [[-1.42791381e-07]
 [-1.42791381e-07]]
2020-01-02 13:26:28,279 - opytimizer.opytimizer — INFO — Optimization task ended.
2020-01-02 13:26:28,279 - opytimizer.opytimizer — INFO — It took 7.672951936721802 seconds.
>>> history.show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'History' object has no attribute 'show'
>>> history
<opytimizer.utils.history.History object at 0x113b75be0>
>>> history.show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'History' object has no attribute 'show'
```

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Virtual Environment: conda `base`
 - Python Version: 

```
(base) justinmai$ python3
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
```

**Additional context**

**Comment by justinTM** [comment]
Does `print(history)` server the same purpose maybe as the older `history.show()`?

**Comment by gugarosa** [comment]
Hello @justinTM! I hope everything is all right with you.

Definitily, ```print(history)``` is serving as the same purpose to the older ```history.show()```. If you look up into the History class implementation, there is a ``` def __str__()``` which implements the same funcionality as the old ```show()```.

If you have any problems or concerns, please let me know!

Best regards,
Gustavo.

**Comment by gugarosa** [comment]
I have also corrected it into the Wiki. Thank you for pointing this out!

**Comment by justinTM** [comment]
Thank you, Gustavo, for your work on this and for the helpful code comments
and general friendliness! Cheers :)

**Comment by gugarosa** [comment]
No problems Justin! I appreciate the help on finding any concerns or issues with the library. I will be closing down this issue and will be updating the wiki with more reliable information in the next few weeks.

If there is anything else, at any time, please let me know!

Best regards,
Gustavo.
